### ISSUE TITLE
'pry' Heroku problem

### ISSUE THREAD

**Issue by eyalev** [wink/money-tree#1]
Hi,

I was having a problem deploying to Heroku. It seems to relate to money-tree/key.rb:4:

require 'pry'

Only when I added 'pry' to production ENV in Gemfile it was fixed.
What is the right solution for this?

Thanks

**Comment by wink** [comment]
Pry was only supposed to be a development dependency, I've removed the require statement, thanks! Go ahead and upgrade to version 0.8.6.

**Comment by eyalev** [comment]
Thanks

**Comment by wink** [comment]
No problem. Thanks for the report.
